### ISSUE TITLE
Class selector rule doesn't allow @-character

### ISSUE THREAD

**Issue by portfolioris** [supple-css/stylelint-config-supple#10]
The selector-class-pattern rule doesn't allow @ characters. This makes it impossible to write something like:

`.o-retain--no-padding\@until-desk`

It's a nice pattern though, and used in Supple-css itself too.

**Comment by bramsmulders** [comment]
I can update the regex for this use case, but the recommended ways to do this in Supple are the following:

- Use of the `responsive.in-query` mixin: https://github.com/supple-kit/supple-css/tree/main/tools#mixin-responsivein-query
- Use `defaults.$responsive-modifier` variable: .selector#{defaults.$responsive-modifier}until-desk {}

**Comment by portfolioris** [comment]
That's cool. The first solution only works with Supple 5, the second solution works for Supple 4 too.
